version: "3.8"

volumes:
  db-data:

services:
  # external services
  gateway:
    image: "traefik:v2.9"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      # NOTE: removed as it's not used right now
      # - --providers.file.filename=/etc/traefik_providers/file_provider.yml
      - --api.dashboard=true
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/traefik_providers"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`, `/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"

  db:
    image: "postgres"
    restart: "always"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adoptapal
      POSTGRES_PASSWORD: adoptapal
      POSTGRES_DB: adoptapal

  # internal services
  auth:
    build:
      context: "./auth"
      dockerfile: "./src/main/docker/Dockerfile.jvm"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"

  user:
    build:
      context: "./user"
      dockerfile: "./src/main/docker/Dockerfile.jvm"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
      - auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/user`)"
      - "traefik.http.routers.user.entrypoints=web"

  animals:
    build:
      context: "./animals"
      dockerfile: "./src/main/docker/Dockerfile.jvm"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.animals.rule=PathPrefix(`/animals`)"
      - "traefik.http.routers.animals.entrypoints=web"

  media:
    build:
      context: "./media"
      dockerfile: "./src/main/docker/Dockerfile.jvm"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=PathPrefix(`/media`)"
      - "traefik.http.routers.media.entrypoints=web"
