site_name: FHE AI MC - Cloud Native Playground Docs

site_url: https://steffen.avemarg.gitlab.io/quarkus-traefik-docker-compose/
site_author: Steffen Avemarg
site_description: >-
  This project demonstrates the usage of various frameworks and techniques for the development 
  of a Microservice application. It is meant as an example for the Mobile Computing 2 course 
  at University of Applied Sciences Erfurt during 2022/23.
  
# Repository
repo_name: pmc-dev/cloud-native-playground
repo_url: https://git.ai.fh-erfurt.de/pmc-dev/cloud-native-playground/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Steffen Avemarg

theme:
  name: material
  palette:
    primary: blue grey
  favicon: img/favicon.png
  icon:
    logo: material/cloud
    repo: fontawesome/brands/gitlab
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Basics: basics.md
  - Resilience: resilience.md
  - Tracing: tracing.md
  - Security: security.md
  - Messaging: messaging.md
  - References: references.md