#------------------------------------
# Local Messaging Endpoint

###
POST http://{{host}}:{{port}}/{{unreliable_srv_base_path}}/messaging

#------------------------------------
# Some Basic Endpoints without any bells and whistle

###
GET http://{{host}}:{{port}}/{{unreliable_srv_base_path}}/base/hello

###
GET http://{{unreliable_srv_full_path}}/base/hello-async

###
GET http://{{unreliable_srv_full_path}}/base/objects
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/base/objects-async
Accept: application/json

#------------------------------------
# Some Endpoints to simulate a more or less reliable Service

###
GET http://{{unreliable_srv_full_path}}/api/single-value
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/single-value-async
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/multiple-values
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/multiple-values-async
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/multiple-values?n=30
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/multiple-values-async?n=3
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/unreliable-single-value
Accept: application/json

###
GET http://{{unreliable_srv_full_path}}/api/unreliable-single-value-async
Accept: application/json

###