### Get response from hello grpc service
GET http://{{dependent_srv_full_path}}/grpc-hello/Max

###
GET http://localhost:8080/grpc-service/

###
GRPC localhost:9000/de.fhe.ai.mc.grpc_service.ContactService/insertContact

{
  "id": 4,
  "firstname": "Max",
  "lastname": "Muster",
  "address": [
    {
      "street": "Hauptstraße",
      "city": "Erfurt",
      "zipCode": "99085",
      "country": "Germany"
    }
  ],
  "location": {
    "latitude": 50.0,
    "longitude": 11.0
  }
}

###
GRPC localhost:9000/de.fhe.ai.mc.grpc_service.ContactService/getAll

###
GRPC localhost:9000/de.fhe.ai.mc.grpc_service.ContactService/getContacts

{
  "searchString": "Max"
}

###
GRPC localhost:9000/de.fhe.ai.mc.grpc_service.ContactService/deleteContact

{
  "contactId": 1
}

###
GRPC localhost:9000/de.fhe.ai.mc.grpc_service.ContactService/updateContact

{
  "id": 1,
  "firstname": "Max",
  "lastname": "Mustermann",
  "address": [
    {
      "street": "Hauptstraße",
      "city": "Erfurt",
      "zipCode": "99085",
      "country": "Germany"
    },
    {
      "street": "Nebenstraße",
      "city": "Erfurt",
      "zipCode": "99099",
      "country": "Germany"
    }
  ],
  "location": {
    "latitude": 50.0,
    "longitude": 11.0
  }
}