#------------------------------------
# Jwt Requests

### Login as Admin
POST http://{{jwt_srv_full_path}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "scott",
  "password": "boss"
}

### Login as User
POST http://{{jwt_srv_full_path}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "jdoe",
  "password": "password"
}

### Request Admin Endpoint
GET http://{{jwt_srv_full_path}}/admin
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FpLmZoLWVyZnVydC5kZSIsInN1YiI6Impkb2UiLCJpYXQiOjE2NzAyNDE1ODQsImV4cCI6MTY3MDI0NTE4NCwiZ3JvdXBzIjpbInVzZXIiXSwibGV2ZWwtb2YtbmVyZGluZXNzIjo0MiwianRpIjoiNTBkZTRkNTMtODBhYi00ZmNhLWFiNTctOGIyYjRkOTcyZjNiIn0.CafkULGkS1zBqNTlLrsP9kcIJNbmDLIlVak3NtgaKjl-sUfyBWVddygX1jMgxOX4hONBbFv3MXUVdWb6nmEQjBH3PbpvZgEFgCNsYfQd2cKI-wSlyIIRjV08eXpPs0TlhkJoamZCglxYlFzbcRGGfMO9F2HaNJMB-VzeoYvcoqacwr1T1lBlXvtGGbcCWSztvLSQjjKdCloa7sa_CKBJdBZbkdz1xw2GGZAPtqM_F14qjKby5AULQ361KkSI8Y_aRk0080KA-3VDBYoEIWfHz76dqQWXlM5MjpvB30WA-SkE6mtzZKW6ePKRrjiMElbLj_M2MKpCGG7LtBSdjC996w

### Request User Endpoint
GET http://{{jwt_srv_full_path}}/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FpLmZoLWVyZnVydC5kZSIsInN1YiI6Impkb2UiLCJpYXQiOjE2NzAyNDE1ODQsImV4cCI6MTY3MDI0NTE4NCwiZ3JvdXBzIjpbInVzZXIiXSwibGV2ZWwtb2YtbmVyZGluZXNzIjo0MiwianRpIjoiNTBkZTRkNTMtODBhYi00ZmNhLWFiNTctOGIyYjRkOTcyZjNiIn0.CafkULGkS1zBqNTlLrsP9kcIJNbmDLIlVak3NtgaKjl-sUfyBWVddygX1jMgxOX4hONBbFv3MXUVdWb6nmEQjBH3PbpvZgEFgCNsYfQd2cKI-wSlyIIRjV08eXpPs0TlhkJoamZCglxYlFzbcRGGfMO9F2HaNJMB-VzeoYvcoqacwr1T1lBlXvtGGbcCWSztvLSQjjKdCloa7sa_CKBJdBZbkdz1xw2GGZAPtqM_F14qjKby5AULQ361KkSI8Y_aRk0080KA-3VDBYoEIWfHz76dqQWXlM5MjpvB30WA-SkE6mtzZKW6ePKRrjiMElbLj_M2MKpCGG7LtBSdjC996w

