version: "3.8"

########################################################
# Volume Definition
########################################################
volumes:
  prom-data:     # Volume to store metrics

services:
  ########################################################
  # Prometheus - Metrics Collector Service
  ########################################################
  prom:
    image: prom/prometheus
    command:
      - --web.external-url=/prom
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - $PWD/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prom.entrypoints=web"
      - "traefik.http.routers.prom.rule=PathPrefix(`/prom`)"
      - "traefik.http.services.prom.loadbalancer.server.port=9090"
