version: "3.8"

services:
  # Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      QUERY_BASE_PATH: /tracing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.entrypoints=web"
      - "traefik.http.routers.jaeger.rule=PathPrefix(`/tracing`)"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"

  ########################################################
  # Auth Service
  ########################################################
  auth-service:
    environment:
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: "${OPEN_TELEMETRY_ENDPOINT}"

  ########################################################
  # JWT Service
  ########################################################
  jwt-service:
    environment:
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: "${OPEN_TELEMETRY_ENDPOINT}"

  ########################################################
  # Unreliable Service
  ########################################################
  unreliable-service:
    environment:
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: "${OPEN_TELEMETRY_ENDPOINT}"

  ########################################################
  # Dependent Service
  ########################################################
  dependent-service:
    environment:
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: "${OPEN_TELEMETRY_ENDPOINT}"