http:
  routers:
    services-weighted-router:
      service: services_weighted
      rule: "PathPrefix(`/services`)"
  services:
    services_weighted:
      weighted:
        services:
          - name: old-service@docker
            weight: 40
          - name: canary-service@docker
            weight: 10